### ISSUE TITLE
Time out in Advanced page

### ISSUE THREAD

**Issue by vdomos** [Nico0084/domogik-plugin-vigilightning#1]
Hi Nico0084,

I got a time out error in "Advanced page" and a "OSError: [Errno 13] Permission denied" in core_admin_http.log.

I just do a ``chmod +x /var/lib/domogik/domogik_packages/plugin_vigilightning/admin/geterrorlog.sh`` to solve the problem.

Now I wait for the next thunderstorms ;)

Nice plugin

**Comment by Nico0084** [comment]
Thanks vdomo,  :)
should be ok now
